apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
data:
  area: planet-v1.18
  public-url: https://maps.endworld.org
  font-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/fonts.tar
  sprite-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/sprite.tar
  natural-earth-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/natural_earth.mbtiles
  mbtiles-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/planet-v1.18.mbtiles
  valhalla-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/planet-v1.18.valhalla.tar
  pelias-config-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/planet-v1.18.pelias.json
  placeholder-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/planet-v1.18.placeholder.tar
  elasticsearch-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/planet-v1.18.elasticsearch.tar
  otp-graph-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/planet-v1.18/planet-v1.18.graph.obj
