apiVersion: apps/v1
kind: Deployment
metadata:
  name: headway-valhalla-deployment
spec:
  selector:
    matchLabels:
      app: valhalla
  replicas: 1
  template:
    metadata:
      labels:
        app: valhalla
    spec:
      initContainers:
        - name: valhalla-init
          image: ghcr.io/headwaymaps/valhalla-init:maps-dot-earth
          imagePullPolicy: Always
          volumeMounts:
            - name: valhalla-volume
              mountPath: /data
          env:
            - name: ARTIFACT_LOCK
              value: /data/imported
            - name: ARTIFACT_URL
              valueFrom:
                configMapKeyRef:
                  name: deployment-config
                  key: valhalla-artifact-url
            - name: HEADWAY_AREA
              valueFrom:
                configMapKeyRef:
                  name: deployment-config
                  key: area
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
      containers:
        - name: valhalla
          image: ghcr.io/headwaymaps/valhalla:maps-dot-earth
          ports:
          - containerPort: 8002
          volumeMounts:
          - name: valhalla-volume
            mountPath: /data
          env:
          - name: HEADWAY_AREA
            valueFrom:
              configMapKeyRef:
                name: deployment-config
                key: area
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 4Gi
      volumes:
        - name: valhalla-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 200Gi
