apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
data:
  area: 0.1.0
  public-url: https://maps.endworld.org
  font-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/fonts.tar
  sprite-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/sprite.tar
  natural-earth-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/natural_earth.mbtiles
  mbtiles-source-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/planet-v1.19/planet-v1.19.mbtiles
  valhalla-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/planet-v1.19/planet-v1.19.valhalla.tar
  pelias-config-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/planet-v1.19/planet-v1.19.pelias.json
  placeholder-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/planet-v1.19/planet-v1.19.placeholder.tar
  elasticsearch-artifact-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/planet-v1.19/planet-v1.19.elasticsearch.tar
  otp-graph-url: https://s3.us-west-004.backblazeb2.com/maps-eotw/0.1.0/planet-v1.19/planet-v1.19.graph.obj
