name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  earthly_build:
    name: Run a build for Adelaide
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Docker login # to avoid dockerhub rate-limiting
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: Earthly version check
        run: earthly --version
      - name: Build Adelaide
        run: earthly -P +build --area=Adelaide --countries=AU
  www_checks:
    defaults:
      run:
        working-directory: web/frontend
    name: Frontend checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test
