name: Push

on:
  push:
    branches: [stable]

jobs:
  build:
    name: Push branded images to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u michaelkirk --password-stdin
      - name: Earthly version check
        run: earthly --version
      - name: Push images
        run: earthly --push +images --tag=maps-dot-earth --branding="maps.earth"
